### ISSUE TITLE
maga firefox maathra yake :/ 

### ISSUE THREAD

**Issue by sddhrthrt** [kirankaranth1/ApplicationStatusFetcher#1]

**Comment by sddhrthrt** [comment]
-_-

**Comment by kirankaranth1** [comment]
Haha.. Firefox is the default driver that selenium uses  To make it compatible with other browsers, need to modify the code swalpa and download some additional drivers. Easier to just install Firefox.
http://stackoverflow.com/questions/13724778/how-to-run-selenium-webdriver-test-cases-in-chrome

**Comment by kirankaranth1** [comment]
Updated README with this :+1:

**Comment by sddhrthrt** [comment]
Yeah, I know that technicality. But I wanted to create the first issue
anyway :P

**Comment by kirankaranth1** [comment]
I don't think there are going to be more issues xD or even ppl who would
use this xD I'm still wondering how you found this repo xD
